version: '3.5'

services:

  alfred_iot_battery_service:
    build: .
    image: alfred_iot_battery_service:latest
    container_name: alfred_iot_battery_service
    restart: always
    hostname: alfred_iot_battery_service
    network_mode: nat